server:
  port: 8080
     
spring:
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         facebook:
          clientId: ${FACEBOOK_CLIENT_ID}
          clientSecret: ${FACEBOOK_CLIENT_SECRET}
          scope:
           - email
           - public_profile      